### PR TITLE
edit handel smb credits SMBException lmn_session_new

### PR DESCRIPTION
**Pull request by ks98**
Hello everyone,

As soon as I selected a class with about 25 students, I immediately received an exception stating that the SMB credits were depleted. Unfortunately, the changes made in the latest updates did not alter this situation. Therefore, I took a closer look at the issue, and with these modifications, I was able to resolve the problems by 80%, even during exam mode.

Perhaps this information will help in resolving the issues.

### CODE REVIEW

**Comment by kiarn** [comment]
Hello @ks98 

Thank you for your feedback and your tests, it's much appreciated, especially because it's the first one I get for session plugin since I patched smbclient methods.  But I think your PR is pretty much the same idea as I used, with notable difference that there's more delay and more attempts.

Using `time.sleep` in an asynchronous environment could lead to block the program. This is here not the case because I monkey patch the whole with `gevent`.

We made a lot of tests the last weeks, and I'm still unable to reproduce the issue on my test server, even with a class containing 600 students. I think my test is simply too slow :)

What I can say about this:
  -  the main reason about this problem is the QoS of samba : https://wiki.samba.org/index.php/SMB2_Credits
  - this problem seems to occur only when the requests are sent parallel. When the requests are sent in sequential mode, the server seems to have enough time to handle all requests and accord credits for the next requests
  - patching smbprotocol to ask one more credit on each request seems to solve completely the problem: https://github.com/jborean93/smbprotocol/blob/b4ce482031cb5a4873cf68d19aaeaee90e5131f8/src/smbprotocol/connection.py#L1244 
```
header["credit_request"] = credit_request if credit_request else credit_charge + 1
```
But this is a bad practice, because we would have to patch this for each update of smbprotocol.

So, I see two solutions:
 - adding some delay and attempts, as you have done, and hoping it's not too long for the end user
 - rewrinting the whole in sequential mode, e.g. here https://github.com/linuxmuster/linuxmuster-webui7/blob/377d3e3444c9a8c44c0d19ed3a4eb72dab197528/usr/lib/linuxmuster-webui/plugins/lmn_session_new/resources/js/services/sessionService.es#L51 no more promises list, but send the user list to Python, and let Python create each directory in a sequential loop.

I can implement both and then fallback in a simplier solution if we can see that less is sufficient.
The main question that I have, since I can not reproduce it: do you hit the error only when creating the working directory, or in another situations ?

Regards,

Arnaud

**Comment by kiarn** [comment]
Done here: c03efd1c0c536f698b8ffa879bbba64858084998
I hope this will definitely solve the problem ...

**Comment by ks98** [comment]
Hello @kiarn ,

Thank you very much for your detailed reply. Unfortunately, I have only now managed to look at everything again. The very latest update with the createWorkingDirectory has solved almost all the problems. Basically, everything works perfectly now. However, as soon as the teacher activates the functions for automatically updating the transfer directory, there are so many errors after about 10 minutes that the credits are used up that only a new login in the GUI helps. Perhaps increasing the interval would help here. For my taste, it would also suffice if there was no interval at all and the teacher always had to press "Refresh".

Thank you very much for your help.


Yours sincerely,
Kevin

**Comment by kiarn** [comment]
Thanks for your feedback, you are the second person saying that the problem with Credit with the working directory is solved. It's a very important point. It's normal that the problem occurs on different events, because I only modified this functionality. I have to switch all other parallel requests to the samba server to sequential.

**Comment by kiarn** [comment]
I moved the folder listing to sequential mode: https://github.com/linuxmuster/linuxmuster-webui7/commit/9b8be3d86dbb6363fd8151811bec6ac3c5992a77

So I think I can close this PR. Thank you for your contribution and feel free to open an issue if the problem persists !

**Pull request closed without merging**
